export enum ICON {
  SORT = "swap_vert",
  ADD = "add",
  CLOSE = "close",
  REDIRECT = "reply",
  MENU = "more_vert",
  ASC_ORDER = "north",
  DESC_ORDER = "south",
  IMAGE = "imagesmode",
  DOWNLOAD = "download",
  DASHBOARD = "dashboard",
  DOCTOR = "local_hospital",
  PATIENTS = "groups",
  APPOINTMENT = "event_note",
  SPECIALTIES = "category",
  INGREDIENTS = "view_comfy",
  SATISFIED = "sentiment_satisfied",
  INGREDIENTS_LIST = "calendar_view_month",
  ADD_INGREDIENTS = "add_box",
  COUPONS = "local_offer",
  CONCERNS = "help_outline",
  REFERRAL = "group_add",
  CUSTOMIZATIONS = "tune",
  WALLET = "account_balance_wallet",
  REFUND = "replay"
}
