export const NavigationRoutes = {
  APP_COMPONENTS: "/app-components",
  HOME: "/*",
  DASHBOARD: "/dashboard",
  DOCTOR: "/doctor",
  PATIENTS: "/patients",
  APPOINTMENT: "/appointment",
  SPECIALTIES: "/specialties",
  INGREDIENTS: "/ingredients",
  INGREDIENTS_LIST: "/ingredients/list",
  ADD_INGREDIENTS: "/ingredients/add",
  EDIT_INGREDIENTS: "/ingredients/edit/:name",
  COUPONS: "/coupons",
  CONCERNS: "/concerns",
  REFERRAL: "/referral",
  CUSTOMIZATIONS: "/customizations",
  WALLET: "/wallet",
  REFUND: "/refund",
  INGREDIENT_DETAILS: "/ingredients/:name",
};

export const AppRoutes = {
  BASE: "/",
  APP_COMPONENTS: "app-components",
  HOME: "/",
  DASHBOARD: "dashboard",
  DOCTOR: "doctor",
  PATIENTS: "patients",
  APPOINTMENT: "appointment",
  SPECIALTIES: "specialties",
  INGREDIENTS: "ingredients",
  INGREDIENTS_LIST: "ingredients/list",
  ADD_INGREDIENTS: "ingredients/add",
  EDIT_INGREDIENTS: "ingredients/edit/:name",
  INGREDIENT_DETAILS: "ingredients/:name",
  COUPONS: "coupons",
  CONCERNS: "concerns",
  REFERRAL: "referral",
  CUSTOMIZATIONS: "customizations",
  WALLET: "wallet",
  REFUND: "refund"
};